//남성&여성 의류 목록
//1~18 남성
//19~35 여성
//36~ 크롤링 의류
//100~세일 상품

//const saleProducts = product.slice(0, 6);
//const manProducts = product.slice(1, 18);
//const womanProducts = product.slice(19, 35);

export const data = {

    product: [
      {
        id: '1',
        name: '터틀넥 Brown',
        image: '/man1.jpg',
        price: 35000,
        rating: 4.0,
        numReviews: 10,
        description: '보온성이 뛰어난 겨울 필수템',
      },
      {
        id: '2',
        name: '베이직 푸퍼 패딩 Black',
        image: '/man2.jpg',
        price: 89000,
        rating: 4.5,
        numReviews: 10,
        description: '한겨울에도 따듯한 패딩',
      },
      {
        id: '3',
        name: 'YALE HOODLE GRAY',
        image: '/man3.jpg',
        price: 29900,
        rating: 4.5,
        numReviews: 14,
        description: '예일대 학생인척 할 수 있는 후드티',
      },
      {
        id: '4',
        name: 'Fallet 티셔츠 White ',
        image: '/man4.jpg',
        price: 17800,
        rating: 4.5,
        numReviews: 10,
        description: '고양이가 포인트인 티셔츠',
      },
      {
        id: '5',
        name: '라운드 니트 Light Green',
        image: '/man5.jpg',
        price: 35000,
        rating: 4.5,
        numReviews: 14,
        description: '부드러운 라운드 니트',
      },
      {
        id: '6',
        name: '와이드 연청 데님 팬츠 ',
        image: '/man6.jpg',
        price: 35900,
        rating: 4.1,
        numReviews: 12,
        description: '사계절용',
      },
      {
        id: '7',
        name: '캐시미어 블렌드 발마칸 코트 Black ',
        image: '/man7.jpg',
        price: 289900,
        rating: 4.5,
        numReviews: 14,
        description: '얼죽코를 위한 코트',
      },
      {
        id: '8',
        name: 'ZIP-UP KNIT NAVY ',
        image: '/man8.jpg',
        price: 56800,
        rating: 4.5,
        numReviews: 10,
        description: '투웨이 집업',
      },
      {
        id: '9',
        name: '화이트라벨 노벨티 눕시 다운 자켓',
        image: '/man9.jpg',
        price: 359900,
        rating: 4.5,
        numReviews: 10,
        description: 'MZ가 되고싶다면 당장 사라',
      },
      {
        id: '10',
        name: ' T-Logo Hoodie Black ',
        image: '/man10.jpg',
        price: 59900,
        rating: 4.0,
        numReviews: 10,
        description: '디스이즈네버댓',
      },
      {
        id: '11',
        name: ' 버핑레더 오버핏 블루종 Suede Brown',
        image: '/man11.jpg',
        price: 57700,
        rating: 4.5,
        numReviews: 14,
        description: '꾸안꾸로 딱인 자켓',
      },
      {
        id: '12',
        name: '삼바 Decon IF0642',
        image: '/man12.jpg',
        price: 179000,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: '데일리템으로 추천',
      },
      {
        id: '13',
        name: ' 트랙 덕다운 베스트 GLOSSY BLACK',
        image: '/man13.jpg',
        price: 118900,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: '덕다운으로 한겨울에도 따듯하게',
      },
      {
        id: '14',
        name: '아플리케 트윌 볼 캡 NAVY',
        image: '/man14.jpg',
        price: 78500,
        countInStock: 13,
        rating: 4.1,
        numReviews: 12,
        description: '랄프로렌',
      },
      {
        id: '15',
        name: '오버사이즈 더플 코트 (다크네이비멜란지)',
        image: '/man15.jpg',
        price: 318000,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: '입자마자 귀여움 뿜뿜',
      },
      {
        id: '16',
        name: '프렌치 치노 투턱 팬츠 (카키 브라운)',
        image: '/man16.jpg',
        price: 47900,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: '모델 강력추천 팬츠',
      },
      {
        id: '17',
        name: '코듀로이 셔츠 Pink',
        image: '/man17.jpg',
        price: 47500,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: '멋쟁이 신사들을 위한 셔츠',
      },
      {
        id: '18',
        name: '빅 트위치 루즈핏 맨투맨 NAVY',
        image: '/man18.jpg',
        price: 28800,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'Lee 로고가 포인트인 맨투맨 ',
      },
        {
          id: '19',
          name: '어그슬리퍼',
          image: '/woman1.jpg',
          price: 73400,
          countInStock: 10,
          rating: 4.5,
          numReviews: 10,
          description: '한겨울에도 따듯한 슬리퍼',
        },
        {
          id: '20',
          name: '플리스자켓 Ivory',
          image: '/woman2.jpg',
          price: 39900,
          countInStock: 0,
          rating: 4.0,
          numReviews: 10,
          description: '아방한 핏으로 귀여움 연출 가능',
        },
        {
          id: '21',
          name: '글로시 크롭 푸퍼 자켓 실버',
          image: '/woman3.jpg',
          price: 55500,
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '크롭이니 참고하시기 바랍니다',
        },
        {
          id: '22',
          name: '비건 스웨이이드 집업 자켓 브라운',
          image: '/woman4.jpg', 
          price: 34900, 
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: '투웨이 집업',
        },
        {
          id: '23',
          name: ' Velour Soccer Jersey Black',
          image: '/woman5.jpg',
          price: 65200,
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '멋쟁이 숙녀들을 위한 맨두맨',
        },
        {
          id: '24',
          name: ' THUNDER 브러쉬드 니트  핑크',
          image: '/woman6.jpg',
          price: 36800,
          countInStock: 13,
          rating: 4.1,
          numReviews: 12,
          description: '사이즈 FREE',
        },
        {
          id: '25',
          name: '니트탑 Black',
          image: '/woman7.jpg',
          price: 24600,
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '사이즈 FREE',
        },
        {
          id: '26',
          name: '키르시 체리 맨투맨 IVORY,',
          image: '/woman8.jpg',
          price: 34500,
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: '사이즈 FREE',
        },
        {
          id: '27',
          name: '핑크 카고 팬츠',
          image: '/woman9.jpg',
          price: 24900,
          countInStock: 10,
          rating: 4.5,
          numReviews: 10,
          description: '블랙핑크 제니 착용',
        },
        {
          id: '27',
          name: '트레이닝 스커트 IVORY',
          image: '/woman10.jpg',
          price: 23500,
          countInStock: 0,
          rating: 4.0,
          numReviews: 10,
          description: '아이브 장원영 착용',
        },
        {
          id: '28',
          name: '트레이닝 팬츠 Black',
          image: '/woman11.jpg',
          price: 19900,
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '재고 5개 남음',
        },
        {
          id: '29',
          name: '브라운 스커트팬츠',
          image: '/woman12.jpg', 
          price: 25100, 
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: '구매시 양말 증정',
        },
        {
          id: '30',
          name: '버킷햇 White',
          image: '/woman13.jpg',
          price: 26900,
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '세탁 주의',
        },
        {
          id: '31',
          name: 'Type Service Web 모자',
          image: '/woman14.jpg',
          price: 31900,
          countInStock: 13,
          rating: 4.1,
          numReviews: 12,
          description: '교환 환불 금지',
        },
        {
          id: '32',
          name: '우포스 쪼리 Black',
          image: '/woman15.jpg',
          price: 49900,
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '단독세일중',
        },
        {
          id: '33',
          name: '춘식이 룸부츠',
          image: '/woman16.jpg',
          price: 39900,
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: '집에서도 따듯한 룸부츠',
        },
        {
          id: '34',
          name: '장갑 Blue',
          image: '/woman17.jpg',
          price: 14500,
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '손목까지 감싸 따듯한 장갑',
        },
        {
          id: '35',
          name: '크롭 가디건',
          image: '/woman18.jpg',
          price: 19900,
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: '르세라핌 홍은채 착용',
        },
        {
          id: '36',
          name: 'Female Hoodie Crop top with Mask',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/5ae4337c11464ccda6050085e4878cf0/embed?ui_theme=dark&dnt=1',
          image: '/36.jpg',
        },
        {
          id: '37',
          name: 'Pencil Skirt Sleeveless Dress',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/0a035326ed6c403183a407baec543604/embed?ui_theme=dark',
          image: '/37.jpg',
        },
        {
          id: '38',
          name: 'Female Turtle-neck one piece',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/9f471178fe004dc180fc612736182100/embed',
          image: '/38.jpg',
        },
        {
          id: '39',
          name: 'Outer / Jumper / Down Jacket',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/de1f1663c8b346ca999247504e9cd605/embed',
          image: '/39.jpg',
        },
        {
          id: '40',
          name: 'Armjak. 19th century.',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/c5a53cf7ffe046e0973590ed6f139da3/embed',
          image: '/40.jpg',
        },
        {
          id: '41',
          name: 'Men Short Sleeved Solid Color Polo',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/670dad551f4243e39f116f5e5e038a5e/embed',
          image: '/41.jpg',
        },
        {
          id: '42',
          name: 'Sage Collection: Cargo Pants',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/ba7b2a55f4f04164bc087ab87322317a/embed',
          image: '/42.jpg',
        },
        {
          id: '43',
          name: 'Men Long Sleeved Collar Stand Polo',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/cbcff5c160854e83a689572d1e3fde83/embed',
          image: '/43.jpg',
        },
        {
          id: '44',
          name: 'Jacket',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/b82c3b5584114a40b6d7e028f680c1d0/embed',
          image: '/44.jpg',
        },
        {
          id: '45',
          name: 'LEATHER JACKET',
          price: `${Math.floor(Math.random() * (100000 - 30000 + 1)) + 30000}`,
          modelSrc:
            'https://sketchfab.com/models/9ae7c88201eb42cdbb072d551c89d042/embed',
          image: '/45.jpg',
        },
        {
          id: '119',
          name: '스튜디오 하트 기모 오버후디',
          image: '/sale19.jpg',
          price: 89900,
          onSale: 'yes',
          priceDrop: 60,
          numReviews: 10,
          description: '원단의 수축 현상을 막기 위해 원단을 정해진 틀에 고정시킨 후 고온으로 건조하여 형태를 단단하게 잡아주는 텐다가공법을 사용하였습니다.',
        },
        {
          id: '120',
          name: '[한정 판매]워셔블 투 톤 크루넥 그래픽 니트 (BLACK)',
          image: '/sale20.jpg',
          price: 52000,
          onSale: 'yes',
          priceDrop: 44,
          numReviews: 10,
          description: 'EASY CARE KNIT',
        },
        {
          id: '113',
          name: '[한정 판매]COOL TO WORK JOGGER PANTS NAVY',
          image: '/sale113.jpg',
          price: 59000,
          onSale: 'yes',
          priceDrop: 21,
          numReviews: 10,
          description: '단독 손세탁 권장',
        },
        {
          id: '114',
          name: '[한정 판매]스포틱스 디비전 스웨트 팬츠-와인',
          image: '/sale114.jpg',
          price: 62000,
          onSale: 'yes',
          priceDrop: 23,
          numReviews: 10,
          description: '밑단 스트링과 스토퍼 디테일로 다양한 실루엣 연출 가능',
        },
        {
          id: '105',
          name: '아식스 X 언어펙티드 젤-카야노 14 - 브라이트 화이트:제트 블랙',
          image: '/sale5.jpg',
          price: 229000,
          onSale: 'yes',
          priceDrop: 19,
          numReviews: 10,
          description: '아식스를 대표하는 라인으로 올해 30주년을 맞이한 KAYANO 모델 중 하나인 GEL-KAYANO 14는 내구성, 편안함 및 우수한 지지력을 자랑하고, 발의 아치를 서포트해 안정성 강화를 위한 Trusstic System®과 GEL® 기술 쿠셔닝이 적용된 오리지널 미드솔 툴링을 반영하는 등 혁신적인 기술을 결합한 고성능 트레이너에서 출발했습니다.',
        },
        {
          id: '106',
          name: 'T.G.I.F 자카드 니트(LIGHT GREY)',
          image: '/sale6.jpg',
          price: 73000,
          onSale: 'yes',
          priceDrop: 30,
          numReviews: 10,
          description: '프라이 슬로건을 그래픽으로 표현한 자카드 니트',
        },
        {
          id: '117',
          name: '옐로우 워싱 와이드 데님팬츠 인디고',
          image: '/sale117.jpg',
          price: 70100,
          onSale: 'yes',
          priceDrop: 33,
          numReviews: 10,
          description: '전면 허벅지부터 무릎으로 갈수록 연해지는 그라데이션 위싱 디테일로 유니크한 컬러로 빈티지한 무드를 보여주는 와이드핏 데님 제품',
        },
        {
          id: '118',
          name: '하버드 우모 퍼 슬리퍼 방한 샌들 베이지',
          image: '/sale118.jpg',
          price: 35000,
          onSale: 'yes',
          priceDrop: 7,
          numReviews: 10,
          description: '하버드 대학교의 공식 라이선스 계약을 통해 제조 및 판매되는 브랜드입니다.',
        },
        {
          id: '109',
          name: '마일백_핑크',
          image: '/sale9.jpg',
          price: 78000,
          onSale: 'yes',
          priceDrop: 11,
          numReviews: 10,
          description: '폭신한 울 원단을 퀄팅하여 가방의 형태가 무너지지 않게 제작하였습니다.',
        },
        {
          id: '110',
          name: 'TONE ON TONE WAPPEN BALL CAP-GREEN',
          image: '/sale10.jpg',
          price: 49000,
          onSale: 'yes',
          priceDrop: 8,
          numReviews: 10,
          description: '바이오 워싱 원단 특성상 스크래치나 노루발 자국이 보일 수 있으며, 이는 불량에 해당되지 않습니다.',
        },
        {
          id: '111',
          name: '빅 사이즈 타탄 체크 머플러 [더스티 크림/블루]',
          image: '/sale11.jpg',
          price: 29900,
          onSale: 'yes',
          priceDrop: 9,
          numReviews: 10,
          description: '캐주얼한 체크패턴 그리고 넓은 폭과 길이로 목을 따듯하게 감싸주는 빅사이즈 타탄 체크 머플러',
        },
        {
          id: '112',
          name: '눕시 온볼 베스트',
          image: '/sale12.jpg',
          price: 189000,
          onSale: 'yes',
          priceDrop: 12,
          numReviews: 10,
          description: '아웃도어 활동 및 일상 생활에도 착용 가능한 스타일',
        },
        {
          id: '113',
          name: 'Matin Kim 가디건 Black',
          image: '/sale13.jpg',
          price: 198000,
          onSale: 'yes',
          priceDrop: 6,
          numReviews: 10,
          description: '뒷면 라인 배색과 마뗑킴 로고가 포인트인 니트 가디건',
        },
        {
          id: '114',
          name: '시그니처 패치 후드집업(기모)',
          image: '/sale14.jpg',
          price: 69900,
          onSale: 'yes',
          priceDrop: 30,
          numReviews: 10,
          description: '코튼 78% 폴리 22%',
        },
        {
          id: '115',
          name: '[한정 판매]피치스킨 러스티 로고 스웨트셔츠 웜그레이',
          image: '/sale15.jpg',
          price: 78000,
          onSale: 'yes',
          priceDrop: 12,
          numReviews: 10,
          description: '겉면 기모 가공으로 부드러운 터치감',
        },
        {
          id: '116',
          name: 'OW LOVE KNIT(BLACK)',
          image: '/sale16.jpg',
          price: 65000,
          onSale: 'yes',
          priceDrop: 13,
          numReviews: 10,
          description: 'y2k 감성 니트',
        },
        {
          id: '117',
          name: '버튼 바라클라바 그레이',
          image: '/sale17.jpg',
          price: 29000,
          onSale: 'yes',
          priceDrop: 7,
          numReviews: 10,
          description: '포인트 아이템으로 레이어드 등 다양한  스타일 연출 가능',
        },
        {
          id: '118',
          name: '[한정 판매]Typeservice Web Cap [Beige Gray]',
          image: '/sale18.jpg',
          price: 39000,
          onSale: 'yes',
          priceDrop: 6,
          numReviews: 10,
          description: '1인 1개 구매 수량 제한',
        },
      ],
  }